package dao;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

import static utils.HibernateUtils.getFactory;
import pojos.Author;
public class AuthorDaoImpl implements Authordao{

	@Override
	public String newAuthor(Author author) {
		String msg="Author added failed....";
		Session session=getFactory().openSession();
		
		Transaction tx=session.beginTransaction();
		try {
			session.persist(author);
			tx.commit();
			msg="added a new author with autogenerated id"+author.getId();
			
			
		}catch (RuntimeException e) {
			if(tx!=null) 
				 tx.rollback();
		}
		return null;
	}

}